language: php

services:
  - mysql

sudo: false

matrix:
  include:
    - env: DBTYPE=mysql; MW=master; TYPE=coverage
      php: 7.3
    - env: DBTYPE=mysql; MW=1.21.0
      php: 5.5
    - env: DBTYPE=sqlite; MW=1.31.0
      php: 7.0
    - env: DBTYPE=sqlite; MW=master
      php: 7.1

before_script: bash ./build/travis/before_script.sh

script: bash ./build/travis/script.sh

after_success: bash ./build/travis/after_success.sh
